[env:esp32s3]
platform  = espressif32
board     = esp32-s3-devkitc-1
board_upload.flash_size = 2MB
framework = espidf
build_flags =
    -std=gnu++17
    -I${PROJECT_DIR}/include
    -I${PROJECT_DIR}/src
    -I${PROJECT_DIR}/src/ui
    -DLV_CONF_INCLUDE_SIMPLE
lib_deps =
    lvgl/lvgl@^9.0.0
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:native]
platform = native
build_flags =
    -std=c++17
    -I${PROJECT_DIR}/include
    -I${PROJECT_DIR}/src
    -I${PROJECT_DIR}/src/ui
    -DLV_CONF_INCLUDE_SIMPLE
    -DLVGL_EMULATOR
    -DSOCKET_PATH=\"/tmp/pi-status.sock\"
    -DDISPLAY_HOR_RES=240
    -DDISPLAY_VER_RES=280
    !pkg-config --cflags --libs sdl2
    !pkg-config --cflags --libs libcjson
lib_deps =
    lvgl/lvgl@^9.0.0
